[build]
  command = "cd apps/styleguide-demo && npm run build"
  publish = "apps/styleguide-demo/dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 